symptoms_dict = {
    "fever": "Mild fever often means your body is fighting an infection. Stay hydrated, rest, and monitor temperature. Seek care if fever exceeds 38.5°C/101.3°F or persists beyond 3 days.",
    "high fever": "High fever may indicate a serious infection. Seek medical advice promptly, especially with chills or confusion.",
    "cough": "A dry cough can be viral (cold/flu) while productive cough may suggest bronchitis. Rest, warm fluids, and humidified air can help.",
    "sore throat": "Throat irritation often improves with warm saltwater gargles and throat lozenges. See a doctor for severe pain or difficulty swallowing.",
    "headache": "Tension headaches can respond to rest, hydration, and OTC pain relievers. If headache is severe or sudden, get urgent evaluation.",
    "nausea": "Nausea can be from food issues, virus, or medication. Eat bland foods, hydrate slowly, and avoid strong smells.",
    "vomiting": "Clear fluids and small sips can prevent dehydration. If persistent beyond 24h or with blood, seek medical care.",
    "diarrhea": "Most cases are viral; drink electrolyte solutions and rest. See provider for blood in stool, severe pain, or dehydration signs.",
    "fatigue": "General fatigue is common with illness, stress, or sleep deficit. Prioritize rest and balanced nutrition; consult if chronic.",
    "dizziness": "Could be dehydration, low blood sugar, or inner ear issue. Sit/lie down until it passes, evaluate for persistent episodes.",
    "chest pain": "Can be heart-related and requires urgent medical evaluation. Do NOT ignore chest discomfort with shortness of breath or sweating.",
    "shortness of breath": "Needs prompt assessment if sudden or severe. Rest, oxygen if prescribed, and contact healthcare provider.",
    "runny nose": "Signs of common cold. Saline nasal spray and steam inhalation help symptom relief.",
    "sneezing": "Often allergic or viral. Consider antihistamine if related to allergies.",
    "rash": "Many rashes are benign; keep clean and monitor. Seek care for spreading, painful, or blistering eruptions.",
    "stomach pain": "Could range from indigestion to infection. Use light meals and hydration; urgent care if severe or with fever/vomiting.",
    "back pain": "Often muscular; stretch, apply heat/cold, and avoid heavy lifting. Seek help for persistent or neurological symptoms.",
    "joint pain": "Common with overuse or inflammation. Rest, cold packs, and anti-inflammatories may help.",
    "muscle pain": "Post-exercise or viral illness. Rest, stretching, and gentle massage ease discomfort.",
    "insomnia": "Good sleep hygiene, reducing screens before bed, and routine can improve sleep. Consult if severe or long lasting.",
    "anxiety": "Breathing exercises and short breaks can help. Consider discussion with a healthcare provider for persistent anxiety.",
    "depression": "Talk to someone trusted and seek professional support for low mood lasting >2 weeks.",
    "loss of taste": "Can occur with viral infections like COVID-19. Monitor and consult if persistent.",
    "loss of smell": "Also seen in respiratory infections. Most recover in weeks, but check with provider if prolonged.",
    "ear pain": "Often ear infection; keep ear dry and seek medical advice if severe.",
    "sweating": "Night sweats or excessive sweating may indicate infection or hormone imbalance. Mention it during medical visits.",
    "tremor": "Occasional shaking may be stress or caffeine; persistent tremor should be assessed by a specialist.",
    "blurred vision": "Can be from eye strain or urgent neurological/vascular issue; get prompt evaluation if sudden.",
    "numbness": "Sudden numbness in limbs or face is a medical emergency (stroke). Seek immediate care.",
}